name: Deploy to VPS

on:
  push:
    branches:
      - master # Change this to the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and update repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/crypto-api/
            git pull origin main 
            docker compose build api
            docker compose up -d --no-deps --build
            docker image prune -f
